# Generated by Django 5.1.4 on 2025-07-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('cam_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('image_thumbnail', models.TextField()),
            ],
            options={
                'db_table': 'cameras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('hub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('chip_id', models.CharField(max_length=20)),
                ('plate_from_chip', models.CharField(max_length=20)),
                ('plate_from_image', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=30)),
                ('tampering_detected', models.BooleanField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'hubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HubLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'hub_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('plate_image', models.BinaryField()),
            ],
            options={
                'db_table': 'Scan_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(default='officer', max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('chip_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRouteLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'vehicle_route_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('image_proof', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'violations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('chip', models.OneToOneField(db_column='chip_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.vehicle')),
                ('fitness_status', models.CharField(max_length=20)),
                ('insurance_status', models.CharField(max_length=20)),
                ('puc_status', models.CharField(max_length=20)),
                ('last_checked', models.DateTimeField()),
            ],
            options={
                'db_table': 'vehicle_documents',
                'managed': False,
            },
        ),
    ]
